/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [2.6.4] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
#include <inttypes.h>
#include <ctime>
#include <iostream>
#include <sys/time.h>

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
uint8_t i = 1;
time_t t;
/* End BUSMASTER global variable */
GCC_EXTERN void GCC_EXPORT OnTimer_node1_10ms_10( );

/* Start BUSMASTER Function Prototype  */
/* Start BUSMASTER generated function - OnTimer_node1_10ms_10 */
void OnTimer_node1_10ms_10( )
{
  STCAN_MSG sMsgStruct;
  sMsgStruct.id = 0x105;
  sMsgStruct.dlc = 8;
  sMsgStruct.cluster = 1;
  sMsgStruct.data[0] = 1;
  SendMsg(sMsgStruct);
}/* End BUSMASTER generated function - OnTimer_node1_10ms_10 */
