/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [2.6.4] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
#include <inttypes.h>
#include <ctime>
#include <iostream>
#include <sys/time.h>

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
uint8_t i = 0;
time_t t;
/* End BUSMASTER global variable */
GCC_EXTERN void GCC_EXPORT OnTimer_5_1milli_1( );

/* Start BUSMASTER generated function - OnTimer_5_1milli_1 */
void OnTimer_5_1milli_1( )
{
  STCAN_MSG sMsgStruct;
  sMsgStruct.id = 0x107;
  sMsgStruct.dlc = 8;
  sMsgStruct.cluster = 1;
  sMsgStruct.data[0] = i % 100;
  i+=2;
  // t = time(0);
  // char* dt = ctime(&t);
  //Trace("i = %d", i);
  //Trace("time=%s",dt);
  SendMsg(sMsgStruct);
  // SendMsg(sMsgStruct);
}/* End BUSMASTER generated function - OnTimer_5_1milli_1 */
